Blog app - creating a data model
aubinleyoung/Blog-app pull request #1
Opened 2023-05-03 21:55 UTC by aubinleyoung

## Blog app - creating a data model
### In this milestone I:

- Built my project schema.
- Created and run the necessary migration files For users, comments, likes, and posts tables .

2023-05-03 22:35 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @aubinleyoung , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: All migrations files correctly added as per project requirements
:heavy_check_mark: Linter checks all passing

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] As per project requirements, the database adapater should be using Postgresql. Currently in your `database.yml` file, your database adapter is sqlite3. Kindly update your database adapter.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 22:35 UTC, t-yanick commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] Great job personalizing the README. Kindly to remove this badge.

2023-05-04 07:30 UTC, peterrobert commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
This change has been done well

2023-05-04 07:43 UTC, peterrobert requested changes
Hi @aubinleyoung, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 07:43 UTC, peterrobert commented on config/database.yml
- [ ] Great work updating your adapter. However, when I try to create a database an error seems to appear. Kindly ensure you can create a Postgres database successfully and can run the migrations successfully. Below is the error that is appearing in my console. ⬇️ 
<img width="874" alt="console error" src="https://user-images.githubusercontent.com/32361963/236141035-2c613e78-9221-4e9d-a19e-0edc0f3c9637.png">

2023-05-04 17:42 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @aubinleyoung :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 17:42 UTC, HAMMAS-SALEEM commented on config/database.yml
> +  database: blog_app_production
![image](https://user-images.githubusercontent.com/93039359/236284084-938d4dcb-55ba-4611-b19e-767834c127ed.png)

- [ ] Great work on implementing the requested changes by I guess your application cannot be created still :fearful: Kindly fix the issue which you can see in the image above :arrow_up:

2023-05-04 17:42 UTC, HAMMAS-SALEEM commented on config/database.yml
>  # Warning: The database defined as "test" will be erased and
![image](https://user-images.githubusercontent.com/93039359/236285238-0e8343b8-4507-4972-a419-3a658146827e.png)

**[OPTIONAL]**

- [ ] It would be nice if you remove the Live Demo sectionn from your readme since you don't have any working live link to make your readme descriptive :+1:

2023-05-04 18:27 UTC, aubinleyoung commented on config/database.yml
> +  database: blog_app_production
Hello @HAMMAS-SALEEM , thank you for your comment, Unfortunently you can not create a new db using my username and password 😄 . Kindly check the image below you will see that my db has been crated with success.
<img width="460" alt="Screenshot 2023-05-04 202110" src="https://user-images.githubusercontent.com/87595063/236294294-6d02063b-6400-4fef-b08b-6b8c820bc80e.png">

2023-05-04 18:39 UTC, prolajumokeoni approved these changes
Hi @aubinleyoung 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
 - Data model created ✅ 
 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 18:48 UTC, merged

2023-05-05 12:00 UTC, HAMMAS-SALEEM commented on config/database.yml
> +  database: blog_app_production
Hey @aubinleyoung I hope that you are doing well 😊

Actually, I am using Ubuntu and in Ubuntu database can be created without a username and password when I tried to make your database then I commented the username and password 🤔 to create the database. But still, I am not able to understand this problem. By the way Sorry for the inconvenience and I would research about it 👍 Thanks for the cooperation 🥇

2023-05-05 12:04 UTC, aubinleyoung commented on config/database.yml
> +  database: blog_app_production
It's okay bro, thanks.