Blog App - processing data in models
aubinleyoung/Blog-app pull request #2
Opened 2023-05-04 22:17 UTC by aubinleyoung

## Blog App - processing data in models
### In this milestone I:
#### Used models to insert data

- Open rails console for your project.
- Created at least one user 
- Created at least 4 posts written by one of the users I created
- Created at least 6 posts comments for one of the posts I created 

#### Created custom methods

> Users

A method that returns the 3 most recent posts for a given user.

> Posts

A method that updates the posts counter for a user.
A method which returns the 5 most recent comments for a given post.

> Comments

A method that updates the comments counter for a post.

> Likes

A method that updates the likes counter for a post.

2023-05-04 22:51 UTC, jerryowusu requested changes
Hi @aubinleyoung 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost there](https://user-images.githubusercontent.com/65233860/236345896-5145d04b-5d61-4bb1-8591-fdbfeca98d26.jpg)


## Highlights
Nice PR description :+1: 
Nice commit messages :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 22:51 UTC, jerryowusu commented on app/models/user.rb
> +end
Kindly make sure that the associations between models are set up correctly according to the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). 
For instance the user modes should have many posts, comments, and likes. 
Remember that author_id column in posts table should be the foreign_key for the users table. 
It should be something like this: 

```ruby
has_many :posts, foreign_key: 'author_id'
has_many :comments, foreign_key: 'author_id'
has_many :likes, foreign_key: 'author_id'
```

2023-05-04 22:51 UTC, jerryowusu commented on app/models/post.rb
> +end
Kindly make sure that the associations between models are set up correctly according to the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). 
For instance the post model should belong to author and has many comments and likes. It should be something like this:

```ruby
belongs_to :author, class_name: 'User'
has_many :comments
has_many :likes
```

2023-05-04 22:51 UTC, jerryowusu commented on app/models/comment.rb
> +end
Kindly make sure that the associations between models are set up correctly according to the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). 
For instance, the comment model should belong to author and post. 
It should be something like this: 

```ruby
belongs_to :author, class_name: 'User'
belongs_to :post
```

2023-05-04 22:51 UTC, jerryowusu commented on app/models/like.rb
> +end
Kindly make sure that the associations between models are set up correctly according to the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). 
For instance, the like model should belong to author and post.
Something like this: 

```ruby
belongs_to :author, class_name: 'User'
belongs_to :post
```

2023-05-05 11:47 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @aubinleyoung, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 11:48 UTC, merged